[project]
name = "milligrad"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = ["numpy"]

[project.optional-dependencies]
dev = ["pytest>=7.0"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
